# Generated by Django 4.0 on 2021-12-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_income_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(default='rwandan', max_length=255, null=True),
        ),
    ]
